### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by iCeY3** [dentolos19/Otakulore#3]
Hello is there an anroid app of this

**Comment by dentolos19** [comment]
Nope. Currently there is no Android version of this project until the stable release of [.NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui) which should be released around the second quarter of 2022.

**Comment by dentolos19** [comment]
As of writing, the Android version is currently in development. However, the development timeline is not definite because I need to study for my upcoming national exams.

**Comment by iCeY3** [comment]
Patiently waiting 😁

And goodluck with your exams!
